name: three
version: 0.3.0-dev
authors:
- Robert Silverton <rob.silverton@gmail.com>
- Nelson Silva <nelson.silva@inevo.pt>
- Adam Singer <financeCoding@gmail.com>
- John <jwbito@gmail.com>
- Anders Forsell http://aforsell.blogspot.com/
- Christopher Grabowski https://github.com/cgrabowski
description: A port of the three.js JavaScript 3D engine to Dart.
homepage: http://threedart.github.com/three.dart/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
  # vector_math: '^2.0.0'
  vector_math:
    git: 'https://github.com/jackd/vector_math.dart.git'
  # change back to pub version if pull request accepted
  quiver: "^0.25.0"
  datgui:
    git: git://github.com/cgrabowski/datgui.git
  stats:
    git: git://github.com/Dartist/stats.dart.git
dev_dependencies:
  unittest: any
